### ISSUE TITLE
您好 很高兴能阅览您的代码，我想问下你在代码中有个函数叫做KNN_DETECT 可是用的不是KMeans聚类方法吗？KNN是分类的，请问这是我理解错了吗？

### ISSUE THREAD

**Issue by Wei-i** [Byronnar/image_classfication#1]
您好 很高兴能阅览您的代码，我想问下你在代码中有个函数叫做KNN_DETECT 可是用的不是KMeans聚类方法吗？KNN是分类的，请问这是我理解错了吗？

**Comment by Byronnar** [comment]
您好,KNN是一种非参数的分类算法,这里面也用到了,但是不是不要的,Kmeans算法也发挥了作用,它将 关键点进行了聚类,下面这个地方:
    kmeans = KMeans(n_clusters=cluster_nums, random_state=randomState).fit(input_x) #关键点聚类
    return kmeans.labels_, kmeans.cluster_centers_

**Comment by Wei-i** [comment]
恩是的 谢谢您的回复，这个表达式我理解 作者我的意思是不是没用KNN的方法嘛 我就是觉得是不是叫做KMeans_Detect 更好点。。 因为是聚类操作。。




------------------ 原始邮件 ------------------
发件人: "Byronnar"<notifications@github.com>;因为
发送时间: 2019年10月16日(星期三) 下午4:45
收件人: "Byronnar/image_classfication"<image_classfication@noreply.github.com>;
抄送: "lost"<845603761@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Byronnar/image_classfication] 您好 很高兴能阅览您的代码，我想问下你在代码中有个函数叫做KNN_DETECT 可是用的不是KMeans聚类方法吗？KNN是分类的，请问这是我理解错了吗？ (#1)




您好,KNN是一种非参数的分类算法,这里面也用到了,但是不是不要的,Kmeans算法也发挥了作用,它将 关键点进行了聚类,下面这个地方:
 kmeans = KMeans(n_clusters=cluster_nums, random_state=randomState).fit(input_x) #关键点聚类
 return kmeans.labels_, kmeans.cluster_centers_

**Comment by Byronnar** [comment]
> 恩是的 谢谢您的回复，这个表达式我理解 作者我的意思是不是没用KNN的方法嘛 我就是觉得是不是叫做KMeans_Detect 更好点。。 因为是聚类操作。。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Byronnar"<notifications@github.com>;因为 发送时间: 2019年10月16日(星期三) 下午4:45 收件人: "Byronnar/image_classfication"<image_classfication@noreply.github.com>; 抄送: "lost"<845603761@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [Byronnar/image_classfication] 您好 很高兴能阅览您的代码，我想问下你在代码中有个函数叫做KNN_DETECT 可是用的不是KMeans聚类方法吗？KNN是分类的，请问这是我理解错了吗？ (#1) 您好,KNN是一种非参数的分类算法,这里面也用到了,但是不是不要的,Kmeans算法也发挥了作用,它将 关键点进行了聚类,下面这个地方: kmeans = KMeans(n_clusters=cluster_nums, random_state=randomState).fit(input_x) #关键点聚类 return kmeans.labels_, kmeans.cluster_centers_ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢你的指出,这样也可以,不然容易造成误解,函数命名确实应该注意,我更新一下仓库.那我把问题关闭了哈

**Comment by Wei-i** [comment]
谢谢作者 给您添麻烦了，哦对了 作者 对于代码我还想向您请教一下可以吗？   就是    
      if des is None:
            file_list.remove(file)
            continue
        reshape_feature = des.reshape(-1, 1)
        features.append(reshape_feature[0].tolist())

    input_x = np.array(features) #计算关键点
    #print(input_x)
    kmeans = KMeans(n_clusters=cluster_nums, random_state=randomState).fit(input_x) #关键点聚类
    return kmeans.labels_, kmeans.cluster_centers_

这一段代码 ，我有2个问题 首先是①对于KMeans.fix（）来说，这个input_x 的输入我看您是只选取了描述子des的reshape成 n*1后的第一个元素(reshape_feature[0])，（我自己print后确实也是这样）
我想问下作者这是根据文档的吗？ 为什么不能是des的所有元素之和的平均数呢？ 第一个元素不会有误差嘛？

**Comment by Wei-i** [comment]
然后第二个小问题就是 
`
if des is None:
file_list.remove(file)
`
因为我自己去网络上获取100张图片的时候 很多次都是运行到一半报出了CV的 NONETYPE的问题 然后经过调试 我发现是图片的问题？ 有些图片的shape就是NONETYPE的，我换了以后就没问题 ， 所以我想问下 作者你加入这段代码的初衷 也是因为有些图片的“问题”还是其他呢？ 我不知道是不是 我自己操作的问题（尴尬）

**Comment by Wei-i** [comment]
@Byronnar 不知道这个关闭问题后您还看不看得到 冒昧at一下

**Comment by Byronnar** [comment]
> 谢谢作者 给您添麻烦了，哦对了 作者 对于代码我还想向您请教一下可以吗？ 就是
> if des is None:
> file_list.remove(file)
> continue
> reshape_feature = des.reshape(-1, 1)
> features.append(reshape_feature[0].tolist())
> 
> ```
> input_x = np.array(features) #计算关键点
> #print(input_x)
> kmeans = KMeans(n_clusters=cluster_nums, random_state=randomState).fit(input_x) #关键点聚类
> return kmeans.labels_, kmeans.cluster_centers_
> ```
> 
> 这一段代码 ，我有2个问题 首先是①对于KMeans.fix（）来说，这个input_x 的输入我看您是只选取了描述子des的reshape成 n*1后的第一个元素(reshape_feature[0])，（我自己print后确实也是这样）
> 我想问下作者这是根据文档的吗？ 为什么不能是des的所有元素之和的平均数呢？ 第一个元素不会有误差嘛？

首先对于这个问题, fit方法可以参考这个网址,它要求的格式是 fit(X[, y])去计算聚类,你说的直接算des所有元素之和我没试过,你可以改一下看一下效果.
这是 kmenas 的一个博客:https://blog.csdn.net/xiaoQL520/article/details/78269539

**Comment by Byronnar** [comment]
> remove

你自己网络上获取图片?爬虫吗? 
出现那个问题,先检查一下那个图片是不是有可能没法打开的,或者文件名是不是不规范,图片的文件名最好统一数字递增命名.

**Comment by 845603761** [comment]
好的谢谢作者，不过我还是不太理解 fit(X[, y])，这里指的应该只是可以只输入X，但对于 组成X的元素我看原博客的X是一种$n \times m$的数组，而这里reshape后 加上只取每个列表的第一个元素，（这里是先获取feature[0]在转化为np的数组形式）维度只是 $n \times 1$？

**Comment by Wei-i** [comment]
好的谢谢作者，不过我还是不太理解 fit(X[, y])，这里指的应该只是可以只输入X，但对于 组成X的元素我看原博客的X是n*m(6 * 2)的数组，而这里reshape后 加上只取每个列表的第一个元素，（这里是先获取feature[0]在转化为np的数组形式）维度只是n * 1？

**Comment by Byronnar** [comment]
维度是n*1啊,我的理解是,kmeans的核心是对点进行聚类,计算它与最近聚类中心(指已选择的聚类中心)的距离D(x), 转换成n*1正是为了将数据变为这种需要的格式,其他的我没试过,你可以自己尝试一下.

**Comment by Wei-i** [comment]
嗯好的 我会在后续的实验中尝试！
但我是感觉作者您和我问的问题好像有点偏差。。。 我的意思是 ，你在变为n*1之前 ，你的n个元素是 通过feature[0]获得的，而我想的是feature列表有好几个元素，为什么只获取他的第一个元素呢?
例:
features.append(reshape_feature[0].tolist())-->>改为features.append（(np.mean(reshape_feature) / np.size(reshape_feature)).tolist()）

**Comment by Byronnar** [comment]
你这样写算出来的是一个一位数组, 不满足聚类要求,fetures列表 里面也不止获取了第一个元素.
reshape_feature [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [2.]]
features [[74.0], [118.0], [72.0], [44.0], [8.0], [0.0], [2.0], [4.0], [9.0], [0.0]]
其他具体的我没有往后研究了,有更好的方法你自己尝试一下吧

**Comment by Wei-i** [comment]
嗯 作者我已经实验出来了 可能我之前我是用ORB算法实现 所以有些地方和您说的不太一样吧。（不过我还是觉得确实只获取第一个元素在添加进列表  print了很多次）
例： 
 reshape_feature_Mean = np.array([np.mean(reshape_feature)])
 features.append(reshape_feature_Mean.tolist())
说下实验结果。。我选了100张图片 聚为10个类  我是感觉效果差不多 （mean的方法 有个别几个图片分为了一类 这是最差的，其他类中我觉得还不错，  只取[0]的话 总体10个类 每个类中的数量比较均衡） 还不清楚为啥 这取第一个元素 和 取平均 居然差距不大 =_=!! 如果作者还想了解更多 可以加我QQ或者到时候我写完发到博客上 O(∩_∩)O  打扰作者了！ 感谢！

**Comment by Byronnar** [comment]
嗯嗯,不客气,互相学习吧, 好好研究吧, 这个项目我也好久没看了, 我最近没把重点放到这个项目,其他事在忙,以后有机会再来看看,你到时候做完了可以把链接放到这个下面,一起学习.

**Comment by Wei-i** [comment]
https://blog.csdn.net/weixin_43823854/article/details/102540793 这是我更新后的博客 ，在此再次感谢下作者对我代码的帮助！ 如果以后有时间我会学习下放置在github上。一起学习！
